name: Generate GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:         # allow manual runs

permissions:
  contents: write            # allow the action to commit the SVG

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # ---- Auth / identity ----
          token: ${{ secrets.GH_PRIVATE_TOKEN }}
          user: Janindu-Amarasekara
          config_timezone: Asia/Colombo

          # ---- Output ----
          filename: metrics.svg
          # (By specifying filename, metrics will commit the SVG to your repo root)

          # ---- Sections / plugins ----
          template: classic
          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_isocalendar: yes
          plugin_stargazers: yes
